name: 'release'
on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: dry run
        type: boolean
        required: false
        default: false
  schedule:
    - cron: '*/5 * * * *'
jobs:
  release:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      EVENT: ${{ toJSON( github.event ) }}
    steps:
      - run: echo "event = $EVENT"
      - run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $1}')" >> $GITHUB_ENV
        shell: bash
      - run: echo "github env = $GITHUB_ENV"
      - uses: decentraland/gh-action-release@0.2.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: ${{ github.event.inputs.dry_run }}
